#!/bin/bash
echo $1
echo $2
/usr/bin/sshpass -p $1 /usr/bin/ssh -o StrictHostKeyChecking=no root@$3 << EOF
/usr/bin/aws ecr get-login-password --region 'ap-south-1' | /usr/bin/docker login --username AWS --password-stdin $2
/usr/bin/docker pull $2:test_image_V1
EOF
